version: '3'

services:
  db:
    container_name: birthdays-db
    image: mongo:5.0.16
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: birthdays-database
    restart: always